name: app_emergencias_cliente
description: App móvil cliente/técnico — plan incremental por casos de uso (sin UI admin/taller).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.2.4
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  record: ^5.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.0
  uuid: ^4.5.1
  flutter_stripe: ^12.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
