/**
 * Optional pre-build step for Vercel: if NG_API_BASE_URL is set, overwrites
 * src/environments/environment.ts with production values (https API + no auth mock).
 * Example: NG_API_BASE_URL=https://emergencias-api.onrender.com/api
 * No trailing slash after /api
 */
/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');
const path = require('path');

const raw = process.env.NG_API_BASE_URL;
if (!raw || !String(raw).trim()) {
  process.exit(0);
}

let u = String(raw).trim();
if (u.endsWith('/')) {
  u = u.replace(/\/+$/, '');
}
if (!u.startsWith('https://') && !u.startsWith('http://')) {
  console.error('vercel-env: NG_API_BASE_URL must be an absolute URL (https://...).');
  process.exit(1);
}

const out = `// Generated by scripts/vercel-env.cjs from NG_API_BASE_URL — do not edit by hand
export const environment = {
  production: true,
  apiUrl: ${JSON.stringify(u)},
  authMock: false,
};
`;

const target = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');
fs.writeFileSync(target, out, 'utf8');
console.log('vercel-env: wrote environment.apiUrl =', u);
